<?php

require_once 'mock/class-speaker-mock.php';

class Hello_Kushimoto_Dashboard_Widget_For_Test extends Hello_Kushimoto_Dashboard_Widget {

	public function get_widget_title_for_test() {
		return $this->get_widget_title();
	}
}

class Test_Hello_Kushimoto_Dashboard_Widget extends WP_UnitTestCase {

//	public function setUp() {
//		parent::setUp(); // TODO: Change the autogenerated stub
//		wp_dashboard_setup();
//	}
//
//	public function test_exsist_widget() {
//		global $wp_meta_boxes;
//		//do_action( 'wp_dashboard_setup' );
//	}

	public function test_sample() {
		$this->assertTrue( true );
	}

	public function test_get_widget_title() {
		$speaker = new Speaker_Mock();
		$obj   = new Hello_Kushimoto_Dashboard_Widget_For_Test( $speaker );
		$title = $obj->get_widget_title_for_test();
		$this->assertEquals( $title, "mock says..." );
	}
}
