<?php

require_once 'mock/class-speaker-mock.php';


class Test_Hello_Kushimoto_Dashboard_Widget extends WP_UnitTestCase {

//	public function setUp() {
//		parent::setUp(); // TODO: Change the autogenerated stub
//		wp_dashboard_setup();
//	}
//
//	public function test_exsist_widget() {
//		global $wp_meta_boxes;
//		//do_action( 'wp_dashboard_setup' );
//	}

	public function test_sample() {
		$this->assertTrue( true );
	}

	public function test_get_title() {
		$title = Closure::bind(function(){
			$speaker = new Speaker_Mock();
			$obj = new Hello_Kushimoto_Dashboard_Widget( $speaker );
			return $obj->get_widget_title();

		}, null, 'Hello_Kushimoto_Dashboard_Widget')->__invoke();

		$this->assertEquals($title, "mock says...");
	}
}
