<?php


class Test_Hello_Kushimoto_Dashboard_Widget extends WP_UnitTestCase {

//	public function setUp() {
//		parent::setUp(); // TODO: Change the autogenerated stub
//		wp_dashboard_setup();
//	}
//
//	public function test_exsist_widget() {
//		global $wp_meta_boxes;
//		//do_action( 'wp_dashboard_setup' );
//	}
}